name: lint_python
on: [push, pull_request] 
jobs:
  lint_python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python_version: "3.8"
      - run: "python -m pip install flake8"
      - run: "python -m flake8 . --count --select=E9,F7,F82 --show-source"
